### ISSUE TITLE
Euler Angles Problem

### ISSUE THREAD

**Issue by ismailtoprak** [ivyknob/bno055_stm32#13]
When I tried to get angles as euler form just you did Euler_X is perfectly correct but euler_y and euler_z are not correct. Suddenly they jump to high degrees. What is the problem, thanks.

**Comment by arrowcircle** [comment]
@ismailtoprak Hi! Could you please provide more information? Demo source code, used hardware, SDK and all other information, that can make it clear what is wrong?

**Comment by wima88** [comment]
@ismailtoprak  Hi , How did you overcome this issue I'm having the same problem?
using F1 with cube IDE 

[log.txt](https://github.com/ivyknob/bno055_stm32/files/6184933/log.txt)

**Comment by wima88** [comment]
please refer to the angular velocity  and linear linear acceleration values in log.txt
