### ISSUE TITLE
Comparison of Libraries

### ISSUE THREAD

**Issue by pkr97** [ivyknob/bno055_stm32#19]
What is the difference between this library and the one provided by BOSCH sensortec? https://github.com/BoschSensortec/BNO055_driver

Best,

**Comment by arrowcircle** [comment]
@pkr97 Hey! This lib have working examples and all the instructions needed to run with STM32

**Comment by pkr97** [comment]
> @pkr97 Hey! This lib have working examples and all the instructions needed to run with STM32

Hi. Thanks for the quick reply. I wanted to know about the difference between these libraries. Is there anything that is not included here compared to the library provided by BOSCH?

**Comment by arrowcircle** [comment]
Never compared. I used only the things I needed.

**Comment by pkr97** [comment]
> Never compared. I used only the things I needed.

OK. Thanks.
