### ISSUE TITLE
Value is jumping

### ISSUE THREAD

**Issue by SoorajR-ai** [ivyknob/bno055_stm32#21]
Value is jumping too high sometimes.
![image](https://github.com/ivyknob/bno055_stm32/assets/106866802/a946064b-35e9-4bbc-988b-9e09efe9cc42)
![image](https://github.com/ivyknob/bno055_stm32/assets/106866802/7d7b0f5e-8080-4df7-a8de-999aa225c5b9)

**Comment by arrowcircle** [comment]
It looks like this is not in the scope of this library.

**Comment by SoorajR-ai** [comment]
Does anyone face this problem?

**Comment by SoorajR-ai** [comment]
I fixed the issue. It was due to stm32f411 i2c pins. using PB9 & PB8 instead of PB7 & PB6 will solve the issue.
