### ISSUE TITLE
Delay in bno055_setOperationMode() ?

### ISSUE THREAD

**Issue by Oliv4945** [ivyknob/bno055_stm32#9]
Why adding 30 ms in bno055_setOperationMode() ?
The datasheet is stating: 19 ms to BNO055_OPERATION_MODE_CONFIG and 7 ms to all others. Did you had issues with those values ?

**Comment by arrowcircle** [comment]
@Oliv4945 Actually I didnt figured out these values and got them from the head.
I think we can test it with 19ms.
Could You please tell why 11 ms is critical in operation mode config? Or just want to be in sync with datasheet?

**Comment by Oliv4945** [comment]
It is not that critical but for battery powered devices I try to avoid spending time full speed for nothing. I changed the function to 
```
void bno055_setOperationMode(bno055_opmode_t mode) {
  bno055_writeData(BNO055_OPR_MODE, mode);
  if (mode == BNO055_OPERATION_MODE_CONFIG) {
	  bno055_delay(19);
  } else {
	  bno055_delay(7);
  }
}
```

If I do no see any issue I will open a PR, it can even be optimized by checking the previous mode
